/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_infinite_labs_platform_core_TestRunner */

#ifndef _Included_net_infinite_labs_platform_core_TestRunner
#define _Included_net_infinite_labs_platform_core_TestRunner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_infinite_labs_platform_core_TestRunner
 * Method:    nativeRunTests
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_infinite_1labs_platform_1core_TestRunner_nativeRunTests
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
