Document: infinitelabs-platform-core
Title: Debian infinitelabs-platform-core Manual
Author: <insert document author here>
Abstract: This manual describes what infinitelabs-platform-core is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/infinitelabs-platform-core/infinitelabs-platform-core.sgml.gz

Format: postscript
Files: /usr/share/doc/infinitelabs-platform-core/infinitelabs-platform-core.ps.gz

Format: text
Files: /usr/share/doc/infinitelabs-platform-core/infinitelabs-platform-core.text.gz

Format: HTML
Index: /usr/share/doc/infinitelabs-platform-core/html/index.html
Files: /usr/share/doc/infinitelabs-platform-core/html/*.html


